/**
 * Task 90 — single fetch wrapper for the static demo build.
 *
 * Non-demo: `apiFetch` is a transparent passthrough to the real `fetch`
 * (byte-identical behavior — the flag is build-time inlined).
 *
 * Demo (static export on GitHub Pages, no server):
 *   - The five known GETs resolve from static fixture files generated by
 *     `npm run demo:fixtures` into `public/demo-fixtures/` and served under
 *     the Pages basePath. A missing fixture throws loudly naming the URL.
 *   - Interactive writes (usage / tracked / activation) SUCCEED as local
 *     no-ops so the optimistic UI state sticks — session-only interactivity.
 *   - Every other non-GET is blocked: an ok=false JSON response the call
 *     sites already tolerate, plus a debounced "Read-only demo" signal that
 *     the demo banner renders as a toast (subscribe via subscribeDemoBlocked).
 */
import { isDemoMode, demoBasePath } from "./demo-mode";

/** Thrown when a demo fixture cannot be fetched/decoded — never fail silently. */
export class DemoFixtureError extends Error {
  constructor(url: string, problem: string) {
    super(`Demo fixture fetch failed for ${url}: ${problem}`);
    this.name = "DemoFixtureError";
  }
}

// ---------------------------------------------------------------------------
// Blocked-write emitter (module-level, debounced so rapid clicks don't stack)
// ---------------------------------------------------------------------------

const BLOCKED_DEBOUNCE_MS = 800;
const blockedListeners = new Set<() => void>();
let lastBlockedEmitMs = 0;

/** Subscribe to "a write was blocked in demo mode" events. Returns unsubscribe. */
export function subscribeDemoBlocked(cb: () => void): () => void {
  blockedListeners.add(cb);
  return () => {
    blockedListeners.delete(cb);
  };
}

/**
 * Signal "a write was blocked in demo mode" → the demo banner renders the
 * read-only modal. Debounced so rapid clicks don't stack. Exported because the
 * Admin re-scrape flow defers this until AFTER its scan animation finishes
 * (the scrape call itself is a silent no-op so the animation plays honestly).
 */
export function emitDemoBlocked(): void {
  const now = Date.now();
  if (now - lastBlockedEmitMs < BLOCKED_DEBOUNCE_MS) return;
  lastBlockedEmitMs = now;
  for (const cb of blockedListeners) cb();
}

// ---------------------------------------------------------------------------
// Demo handlers
// ---------------------------------------------------------------------------

function jsonResponse(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

/** Fetches one generated fixture as a static asset (basePath-prefixed). */
async function loadFixture(name: string): Promise<unknown> {
  const url = `${demoBasePath}/demo-fixtures/${name}.json`;
  let res: Response;
  try {
    res = await fetch(url);
  } catch (err) {
    throw new DemoFixtureError(url, `network error (${String(err)})`);
  }
  if (!res.ok) {
    throw new DemoFixtureError(url, `HTTP ${res.status} — did "npm run demo:fixtures" run before the demo build?`);
  }
  return res.json();
}

const BENEFITS_BY_CARD_RE = /^\/api\/user-cards\/([^/]+)\/benefits$/;

/** Demo GET → fixture data. Unknown /api GETs throw loudly (no silent empty UI). */
async function demoGet(path: string): Promise<Response> {
  if (path === "/api/overview") return jsonResponse(await loadFixture("overview"));
  if (path === "/api/user-cards") return jsonResponse(await loadFixture("user-cards"));
  if (path === "/api/portfolio/stats") return jsonResponse(await loadFixture("portfolio-stats"));
  if (path === "/api/catalog") return jsonResponse(await loadFixture("catalog"));

  const benefitsMatch = BENEFITS_BY_CARD_RE.exec(path);
  if (benefitsMatch) {
    const byCard = (await loadFixture("benefits-by-card")) as Record<string, unknown>;
    const rows = byCard[benefitsMatch[1]];
    if (rows === undefined) {
      throw new DemoFixtureError(
        `${demoBasePath}/demo-fixtures/benefits-by-card.json`,
        `no entry for userCard id "${benefitsMatch[1]}"`,
      );
    }
    return jsonResponse(rows);
  }

  throw new Error(`apiFetch (demo): no fixture mapped for GET ${path}`);
}

/** True for the writes that no-op successfully (optimistic state sticks). */
function isInteractiveWrite(path: string, method: string): boolean {
  if (method === "POST" && /^\/api\/benefits\/[^/]+\/usage$/.test(path)) return true;
  if (method === "PATCH" && /^\/api\/benefits\/[^/]+$/.test(path)) return true;
  if (
    (method === "PATCH" || method === "POST") &&
    /^\/api\/benefits\/[^/]+\/activation$/.test(path)
  ) {
    return true;
  }
  return false;
}

/**
 * Demo re-scrape: a silent no-op success (empty result, NO blocked-emit) so the
 * Admin scan animation plays through honestly. The admin flow shows the
 * read-only modal itself once the animation settles (scan-then-modal), instead
 * of the negative "Failed to scrape" screen a 403 would trigger.
 */
function isScrape(path: string, method: string): boolean {
  return method === "POST" && /^\/api\/user-cards\/[^/]+\/scrape$/.test(path);
}

/** Demo non-GET: interactive writes succeed as no-ops; everything else blocks. */
function demoWrite(path: string, method: string, init?: RequestInit): Response {
  if (isScrape(path, method)) {
    return jsonResponse({ benefits: [], annualFee: null });
  }
  if (!isInteractiveWrite(path, method)) {
    emitDemoBlocked();
    return jsonResponse({ error: "Read-only demo" }, 403);
  }
  if (/\/activation$/.test(path)) {
    // ActivationToggle reads `activatedAt` from the response body.
    const body = typeof init?.body === "string" ? (JSON.parse(init.body) as { activated?: boolean }) : {};
    return jsonResponse({ activatedAt: body.activated ? new Date().toISOString() : null });
  }
  // Usage POST / tracked PATCH call sites only check res.ok.
  return jsonResponse({ ok: true });
}

// ---------------------------------------------------------------------------
// Public wrapper
// ---------------------------------------------------------------------------

function requestPath(input: RequestInfo | URL): string {
  if (typeof input === "string") return input.split("?")[0];
  if (input instanceof URL) return input.pathname;
  return new URL(input.url).pathname;
}

/**
 * Drop-in replacement for `fetch` on every internal /api call. Non-demo mode
 * passes straight through; demo mode serves fixtures / no-ops / blocks.
 */
export async function apiFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  if (!isDemoMode) return fetch(input, init);

  const path = requestPath(input);
  if (!path.startsWith("/api/")) return fetch(input, init);

  const method = (init?.method ?? "GET").toUpperCase();
  if (method === "GET") return demoGet(path);
  return demoWrite(path, method, init);
}
